// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwfplbsNS4KtKdPgRjxcUX38fNW8Rg7g',
    appId: '1:228027381198:web:0ce2268f1d77d56c86e79f',
    messagingSenderId: '228027381198',
    projectId: 'carregisterapp',
    authDomain: 'carregisterapp.firebaseapp.com',
    storageBucket: 'carregisterapp.firebasestorage.app',
    measurementId: 'G-1N9XFDRSMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI2J7iTJBL7IkkLg4pNdW1xOHqI1680ew',
    appId: '1:228027381198:android:8c192c90dc1a429d86e79f',
    messagingSenderId: '228027381198',
    projectId: 'carregisterapp',
    storageBucket: 'carregisterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVg7br13Gb_6F7CygVCNAXuAq0EPSl4M4',
    appId: '1:228027381198:ios:b43fa0954dd3a90f86e79f',
    messagingSenderId: '228027381198',
    projectId: 'carregisterapp',
    storageBucket: 'carregisterapp.firebasestorage.app',
    iosBundleId: 'com.example.carRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVg7br13Gb_6F7CygVCNAXuAq0EPSl4M4',
    appId: '1:228027381198:ios:b43fa0954dd3a90f86e79f',
    messagingSenderId: '228027381198',
    projectId: 'carregisterapp',
    storageBucket: 'carregisterapp.firebasestorage.app',
    iosBundleId: 'com.example.carRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADwfplbsNS4KtKdPgRjxcUX38fNW8Rg7g',
    appId: '1:228027381198:web:7bb3384437a23f0c86e79f',
    messagingSenderId: '228027381198',
    projectId: 'carregisterapp',
    authDomain: 'carregisterapp.firebaseapp.com',
    storageBucket: 'carregisterapp.firebasestorage.app',
    measurementId: 'G-VMXSLGKQYS',
  );
}
